import {
  ArrowDownRight,
  ArrowLeftRight,
  ArrowUpRight,
  Banknote,
  Bike,
  Briefcase,
  Building2,
  Bus,
  Car,
  CarTaxiFront,
  CalendarClock,
  Check,
  CircleAlert,
  CirclePlus,
  Coffee,
  CreditCard,
  Database,
  Download,
  Droplets,
  Dumbbell,
  FileText,
  Fuel,
  Gamepad2,
  Gift,
  Hammer,
  HandCoins,
  HeartHandshake,
  House,
  KeyRound,
  Landmark,
  Laptop,
  LayoutDashboard,
  Percent,
  PiggyBank,
  Plane,
  Plug,
  Receipt,
  Repeat,
  Settings,
  ShoppingBag,
  ShoppingBasket,
  Smartphone,
  Sparkles,
  SprayCan,
  Stethoscope,
  Tag,
  Target,
  TrendingUp,
  Undo2,
  UtensilsCrossed,
  Wallet,
  Wifi,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

/**
 * A closed registry rather than a dynamic import of all of lucide: the seeds
 * and the category editor can only ever reference these, and shipping the whole
 * icon set to render forty of them is a waste of a megabyte.
 */
export const ICONS: Record<string, LucideIcon> = {
  ArrowDownRight,
  ArrowLeftRight,
  ArrowUpRight,
  Banknote,
  Bike,
  Briefcase,
  Building2,
  Bus,
  CalendarClock,
  Car,
  CarTaxiFront,
  Check,
  CircleAlert,
  CirclePlus,
  Coffee,
  CreditCard,
  Database,
  Download,
  Droplets,
  Dumbbell,
  FileText,
  Fuel,
  Gamepad2,
  Gift,
  Hammer,
  HandCoins,
  HeartHandshake,
  House,
  KeyRound,
  Landmark,
  Laptop,
  LayoutDashboard,
  Percent,
  PiggyBank,
  Plane,
  Plug,
  Receipt,
  Repeat,
  Settings,
  ShoppingBag,
  ShoppingBasket,
  Smartphone,
  Sparkles,
  SprayCan,
  Stethoscope,
  Tag,
  Target,
  TrendingUp,
  Undo2,
  UtensilsCrossed,
  Wallet,
  Wifi,
  Wrench,
  Zap,
};

export function iconFor(name: string | null | undefined): LucideIcon {
  if (!name) return Tag;
  return ICONS[name] ?? Tag;
}
